### ISSUE TITLE
Update doc.md of each provider

### ISSUE THREAD

**Issue by Marzz29** [opensaucerer/bifrost#20]
### Title 
Update documentation for cloud service providers with different methods for using Bifrost

### Description

The current documentation for Bifrost only provides a general guide on how to use the tool. To ensure that users have a better understanding of how to use Bifrost with different cloud service providers, we need to update the documentation to include detailed guides for each provider.

This issue aims to update the documentation for each cloud service provider that contains different methods on how to use Bifrost. The updated documentation will provide users with a comprehensive guide on how to use Bifrost with their preferred cloud service provider.

To achieve this, we will create a new doc file for each provider in the package folder. These files will contain detailed instructions on how to mount a bridge for the provider and how to use each method available for such provider. All the methods actually... (UploadFile, UploadMultiFile, Disconnect, Config, IsConnected, etc...)

The following providers will be included:

- Google Cloud Storage (GCS)

- Amazon Web Services (AWS) S3

- Pinata Cloud

Each provider doc file will include the following sections:

- Introduction to Bifrost and the provider
- Prerequisites for using Bifrost with the provider
- Configuring Bifrost for the provider
- Methods for using Bifrost with the provider
- Troubleshooting common issues

By updating the documentation with detailed guides for each cloud service provider, users will have a better understanding of how to use Bifrost effectively with their preferred provider. This will improve the overall user experience and make Bifrost a more useful tool for developers.

This issue will require collaboration from the community to ensure that the documentation is accurate and up-to-date. Contributors are welcome to submit pull requests with improvements to the documentation for any provider.

**Comment by opensaucerer** [comment]
Looking forward to the PR for this... just a tiny note that we should probably not put in "troduction to Bifrost" as that's already covered in the readme and based on the readme's call to action, people who visit `doc.md` are majorly there to see the methods of the providers in action.

**Comment by Marzz29** [comment]
Okay no problem

**Comment by opensaucerer** [comment]
Resolved already.
