### ISSUE TITLE
add some validations

### ISSUE THREAD

**Issue by ShowBaba** [opensaucerer/bifrost#21]
add validations to some inputs like filename and file path (should contain a file extension), this might cause the file URL to be invalid

**Comment by opensaucerer** [comment]
True...let's create a new bifrost error code called `ErrInvalidParameters` so we have something like 
```go
return nil, &errors.BifrostError{
	Err:       err,
	ErrorCode: errors.ErrInvalidParameters,
}
```

**Comment by opensaucerer** [comment]
Resolved
